### ISSUE TITLE
Is everything looking good?

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [mine-cetinkaya-rundel/feed-me-back#12]
We actually managed to do this with minimal merge conflicts, woohoo!

It's looking good to me. Want to review your slides to make sure I didn't bork anything @ttimbers?

I've linked to [bit.ly/feed-me-back](https://bit.ly/feed-me-back) from the slides which has a link to slides and the repo in one place.

**Comment by ttimbers** [comment]
Whoohoo indeed! And we worked well across timezones to boot! Also thanks for making the slides beautiful!

My slides look good to me, looking forward to this! We have 30 min for our session, so we each talk for about 10-12 min? to leave 5-10 min for questions? Is that right?

**Comment by mine-cetinkaya-rundel** [comment]
Yeah, that's what I was thinking. 

One change I'm still contemplating is to move the FAQ slides I have to the end. If we get to them, great. And if not, they're self-explanatory (and we can follow up in the blog post too). What do you think?

**Comment by ttimbers** [comment]
Sounds good to me!
