### ISSUE TITLE
Add mybinder functionality

### ISSUE THREAD

**Issue by ttimbers** [mine-cetinkaya-rundel/feed-me-back#3]
I am going to add binder functionality for my demo. I assume you don't need that for yours?

**Comment by mine-cetinkaya-rundel** [comment]
No, I don't need it for mine.

**Comment by ttimbers** [comment]
I think something in this repo clashed with binder (something Rmd/Xaringan related perhaps?) and so I had to setup the binder demo in another repo ([here](https://github.com/ttimbers/jupyter-demo)), but linked to it in the talk and in the examples README.
